name = "Charm Craft"
client_id = "f111ef9fd18130fc895780673cab117c"
application_url = "https://charmcraft-seven.vercel.app"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_metafields,write_metafields,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://charmcraft-seven.vercel.app/api/auth/callback",
  "http://localhost:3001/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  topics = ["products/update"]
  uri = "/api/webhooks"

[app_proxy]
url = "https://charmcraft-seven.vercel.app/api/proxy"
subpath = "charmcraft"
prefix = "apps"

[pos]
embedded = false
